### ISSUE TITLE
Old runs cannot be processed 

### ISSUE THREAD

**Issue by lucabaldini** [centrofermi/e3pipe#65]
The name of the stations has changed along the way, e.g., SAVO-01 used to be SVC-01 before October 10, 2014 and SAVO-02 used to be SVG-01.

The processing pipeline cannot currently handle this, as there is a unique correspondence between the station name and the station unique id. Before we event think about tweaking the pipeline we should consider renaming the old files, as otherwise bookkeeping will become a nightmare. This might be non trivial due due to the synchronizations with the schools.

**Comment by noferini** [comment]
Now this issue should be resolved (files were renamed)
